### ISSUE TITLE
Problem with auto.master

### ISSUE THREAD

**Issue by RasmusGOlsen** [cmprescott/ansible-role-autofs#16]
When auto.master has updated the path to auto.nfs is not added, only the filename. Is that correct?

The lines added looks like:
/mnt/nfs auto.nfs

shouldn't it be:
/mnt/nfs /etc/auto.fs

**Comment by Doc-Tiebeau** [comment]
No because autofs configuration files parsing uses relative path based on auto.master path as root config directory.
